FROM node:16-alpine

WORKDIR /app

# 设置npm淘宝镜像源
RUN npm config set registry https://registry.npmmirror.com

# 安装依赖
COPY package*.json ./
RUN npm install

# 开发模式启动
EXPOSE 8080
CMD ["npm", "run", "serve"] 